name: darkblue
description: A custom uBlue image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling
    install:
      - justfiles
      - nix-installer

  - type: yafti
    custom-flatpaks:

  - type: script
    scripts:
      - signing.sh
