name: darkblue
description: A custom uBlue image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - etc: /etc
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
      - code
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tour

  - type: bling
    install:
      - dconf-update-service
      - nix-installer

  - type: yafti
    custom-flatpaks:

  - type: script
    scripts:
      - cleanup.sh
      - signing.sh
